cuarto_semestre/backend/unidad_1/ejercicios/django/evaluacion/clientes/urls.py
from django.urls import path

from . import views

app_name = 'clientes'
urlpatterns = [
    path('', views.planes, name='planes'),
    path('lista', views.lista, name='lista')
]

cuarto_semestre/backend/unidad_1/ejercicios/django/evaluacion/clientes/views.py
from django.shortcuts import render

def planes(request):
    if request.method == 'POST':
        rut = request.POST['rut']
        nombre = request.POST['nombre']
        telefono = request.POST['telefono']
        correo = request.POST['correo']
        direccion = request.POST['direccion']
        plan = request.POST['plan']
        comentario = request.POST['comentario']

        registro = f'{rut}|{nombre}|{telefono}|{correo}|{direccion}|{plan}|{comentario}\n'

        with open('infoplanes.txt', 'a') as archivo:
            archivo.write(registro)

    return render(request, 'clientes/planes.html')

def lista(request):
    clientes = []

    with open('infoplanes.txt', 'r') as archivo:
        for linea in archivo.readlines():
            cliente = []

            for elemento in linea.rstrip('\n').split('|'):
                cliente.append(elemento)

            clientes.append(cliente)

    return render(request, 'clientes/lista.html', {
        'clientes': clientes
    })

cuarto_semestre/backend/unidad_1/ejercicios/django/evaluacion/clientes/templates/clientes/lista.html
{% extends 'clientes/plantilla.html' %}

{% block cuerpo %}

<h2 class="text-center">Lista de clientes</h2>
<p class="text-center"><a href="{% url 'clientes:planes' %}">Contratar plan</a></p>

{% if clientes|length > 0 %}
<table class="table">
    <tr>
        <td>Rut</td>
        <td>Nombre</td>
        <td>Teléfono</td>
        <td>Correo</td>
        <td>Dirección</td>
        <td>Plan</td>
        <td>Comentario</td>
    </tr>
    {% for cliente in clientes %}
    <tr>
        {% for elemento in cliente %}
        <td>{{ elemento }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock cuerpo %}

cuarto_semestre/backend/unidad_1/ejercicios/django/evaluacion/clientes/templates/clientes/planes.html
{% extends 'clientes/plantilla.html' %}

{% block cuerpo %}

<h2 class="text-center">Formulario planes</h2>

<p class="text-center"><a href="{% url 'clientes:lista' %}">Ver clientes</a></p>

<form method="post">
    {% csrf_token %}

    <!-- Rut -->
    <label for="rut">Rut: </label>
    <input type="text" name="rut" id="rut" required pattern="^\d{1,2}\.\d{3}\.\d{3}-[\dkK]$" title="12.345.678-9"
        placeholder="12.345.678-9">
    <br>

    <!-- Nombre -->
    <label for="nombre">Nombre: </label>
    <input type="text" name="nombre" id="nombre" required pattern="^\S.*" title="No empiece con espacios">
    <br>

    <!-- Teléfono -->
    <label for="telefono">Teléfono: </label>
    <input type="tel" name="telefono" id="telefono" required pattern="^\+569\d{8}$" title="+56912345678"
        placeholder="+56912345678">
    <br>

    <!-- Correo -->
    <label for="correo">Correo: </label>
    <input type="email" name="correo" id="correo" required title="Ingrese un correo válido">
    <br>

    <!-- Dirección -->
    <label for="direccion">Dirección: </label>
    <input type="text" name="direccion" id="direccion" required pattern="^\S.*" title="No empiece con espacios"
        minlength="20">
    <br>

    <!-- Plan -->
    <label for="plan">Plan: </label>
    <select name="plan" id="plan">
        <option value="S">S - $15990</option>
        <option value="M">M - $19990</option>
        <option value="L">L - $29990</option>
    </select>
    <br>

    <!-- Comentario -->
    <label for="comentario">Comentario: </label>
    <textarea name="comentario" id="comentario" cols="30" rows="10" required minlength="30"></textarea>
    <br>

    <!-- Enviar -->
    <input type="submit" value="Contratar plan">

    <!-- Limpiar -->
    <input type="reset" value="Limpiar formulario">

</form>

{% endblock cuerpo %}

cuarto_semestre/backend/unidad_1/ejercicios/django/evaluacion/clientes/templates/clientes/plantilla.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Planes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>
<body>
    <h1 class="text-center">Planes</h1>

    {% block cuerpo %}
    {% endblock cuerpo %}

</body>
</html>