cuarto_semestre/backend/unidad_2/proyecto001/categorias/urls.py
from django.urls import path
from categorias import views

app_name = 'categorias'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('crear/', views.crear, name='crear'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
    path('actulizar/<int:id>', views.actualizar, name='actualizar')
]

cuarto_semestre/backend/unidad_2/proyecto001/marcas/urls.py
from django.urls import path

from . import views
app_name = 'marcas'

urlpatterns = [
    path('', views.listar, name='listar'),
    path('crear', views.crear, name='crear'),
    path('actualizar/<int:id>', views.actualizar, name='actualizar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar')
]

cuarto_semestre/backend/unidad_2/proyecto001/proyecto001/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('personas/', include('personas.urls')),
    path('marcas/', include('marcas.urls')),
    path('categorias/', include('categorias.urls')),
    path('productos/', include('productos.urls'))
]

cuarto_semestre/backend/unidad_2/proyecto001/categorias/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

cuarto_semestre/backend/unidad_2/proyecto001/categorias/forms.py
from django.forms import ModelForm, widgets
from categorias.models import Categoria

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {
            'nombre': widgets.TextInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }

cuarto_semestre/backend/unidad_2/proyecto001/categorias/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from categorias.models import Categoria
from categorias.forms import CategoriaForm


def listar(request):
    categorias = Categoria.objects.all()
    return render(request, 'categorias/listar.html', {
        'categorias': categorias
    })


def eliminar(_, id):
    categoria = Categoria.objects.get(id=id)
    categoria.delete()
    return redirect(reverse('categorias:listar'))


def crear(request):
    formulario = CategoriaForm()

    if request.method == 'POST':
        formulario = CategoriaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('categorias:listar'))

    return render(request, 'categorias/crear.html', {
        'formulario': formulario,
        'titulo': 'Crear categoria'
    })


def actualizar(request, id):
    categoria = Categoria.objects.get(id=id)
    formulario = CategoriaForm(instance=categoria)

    if request.method == 'POST':
        formulario = CategoriaForm(request.POST, instance=categoria)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('categorias:listar'))

    return render(request, 'categorias/crear.html', {
        'formulario': formulario,
        'titulo': 'Actualizar categoria'
    })

cuarto_semestre/backend/unidad_2/proyecto001/categorias/templates/categorias/crear.html
{% extends 'categorias/plantilla.html' %}

{% block contenido %}
<div class="container">
    <h1>{{ titulo }}</h1>
    <form method="post">
        {{ formulario }}
        {% csrf_token %}
    </form>
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/proyecto001/categorias/templates/categorias/listar.html
{% extends 'categorias/plantilla.html' %}

{% block contenido %}
<div class="container">
    {% if categorias %}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Actualizar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
            <tr>
                <td>{{ categoria.id }}</td>
                <td>{{ categoria.nombre }}</td>
                <td>
                    <a href="{% url 'categorias:actualizar' categoria.id %}" class="btn">⟳</a>
                </td>
                <td>
                    <a href="{% url 'categorias:eliminar' categoria.id %}" class="btn">X</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>No hay categorías</h3>
    {% endif %}
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/proyecto001/categorias/templates/categorias/plantilla.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</head>

<body>
    {% block contenido %}
    {% endblock contenido %}
</body>

</html>