cuarto_semestre/backend/unidad_2/evaluacion/evaluacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tipos/', include('tipos.urls')),
    path('', include('mascotas.urls')),
]

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/urls.py
from django.urls import path
from mascotas import views

app_name = 'mascotas'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('crear', views.crear, name='crear'),
    path('actualizar/<int:id>', views.actualizar, name='actualizar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
]

cuarto_semestre/backend/unidad_2/evaluacion/tipos/urls.py
from django.urls import path
from tipos import views

app_name = 'tipos'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('crear', views.crear, name='crear'),
]

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/models.py
from django.db import models
from tipos.models import Tipo


class Mascota(models.Model):
    nombre = models.CharField(max_length=30)
    tipo = models.ForeignKey(Tipo, on_delete=models.RESTRICT)

cuarto_semestre/backend/unidad_2/evaluacion/tipos/models.py
from django.db import models


class Tipo(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/forms.py
from django.forms import ModelForm, widgets
from mascotas.models import Mascota


class MascotaFormulario(ModelForm):
    class Meta:
        model = Mascota
        fields = '__all__'
        widgets = {
            'nombre': widgets.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'tipo': widgets.Select(
                attrs={
                    'class': 'form-select'
                }
            )
        }

cuarto_semestre/backend/unidad_2/evaluacion/tipos/forms.py
from django.forms import ModelForm, widgets
from tipos.models import Tipo


class TipoFormulario(ModelForm):
    class Meta:
        model = Tipo
        fields = '__all__'
        widgets = {
            'nombre': widgets.TextInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from mascotas.forms import MascotaFormulario
from mascotas.models import Mascota


def listar(request):
    mascotas = Mascota.objects.all()

    return render(request, 'mascotas/listar.html', {
        'mascotas': mascotas
    })


def crear(request):
    formulario = MascotaFormulario()

    if request.method == 'POST':
        formulario = MascotaFormulario(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('mascotas:listar'))

    return render(request, 'mascotas/crear.html', {
        'formulario': formulario
    })


def actualizar(request, id):
    mascota = Mascota.objects.get(id=id)
    formulario = MascotaFormulario(instance=mascota)

    if request.method == 'POST':
        formulario = MascotaFormulario(request.POST, instance=mascota)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('mascotas:listar'))

    return render(request, 'mascotas/crear.html', {
        'formulario': formulario
    })


def eliminar(_, id):
    mascota = Mascota.objects.get(id=id)
    mascota.delete()
    return redirect(reverse('mascotas:listar'))

cuarto_semestre/backend/unidad_2/evaluacion/tipos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from tipos.forms import TipoFormulario
from tipos.models import Tipo


def listar(request):
    tipos = Tipo.objects.all()

    return render(request, 'tipos/listar.html', {
        'tipos': tipos
    })


def crear(request):
    formulario = TipoFormulario()

    if request.method == 'POST':
        formulario = TipoFormulario(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('tipos:listar'))

    return render(request, 'tipos/crear.html', {
        'formulario': formulario
    })

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/templates/mascotas/crear.html
{% extends 'mascotas/plantilla.html' %}

{% block contenido %}
<div class="container">
    <h1 class="text-center">Crear mascota</h1>
    <h4 class="text-center">
        <a href="{% url 'mascotas:listar' %}">Listado de mascotas</a>
    </h4>
    <form method="post">
        {% csrf_token %}
        {{ formulario }}
        <input type="submit" class="form-control">
    </form>
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/templates/mascotas/listar.html
{% extends 'mascotas/plantilla.html' %}

{% block contenido %}
<div class="container">
    <h1 class="text-center">Listado de mascotas</h1>
    <h4 class="text-center">
        <a href="{% url 'mascotas:crear' %}">Crear una mascota</a>
    </h4>
    {% if mascotas %}
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Actualizar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for mascota in mascotas %}
            <tr>
                <td>{{ mascota.nombre }}</td>
                <td>{{ mascota.tipo }}</td>
                <td>
                    <a href="{% url 'mascotas:actualizar' mascota.id %}" class="btn btn-secondary">⟳</a>
                </td>
                <td>
                    <a href="{% url 'mascotas:eliminar' mascota.id %}" class="btn btn-secondary">X</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>No hay mascotas</h3>
    {% endif %}
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/evaluacion/mascotas/templates/mascotas/plantilla.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mascotas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</head>

<body>

    <!-- Barra de navegación improvisada que hice en el momento -->
    <div class="container text-center my-3">
        <div class="row">
            <div class="col">
                <h1>
                    <a href="{% url 'tipos:listar' %}" class="text-decoration-none">Tipos</a>
                </h1>
            </div>
            <div class="col">
                <h1>
                    <a href="{% url 'mascotas:listar' %}" class="text-decoration-none">Mascotas</a>
                </h1>
            </div>
        </div>
    </div>

    {% block contenido %}
    {% endblock contenido %}
</body>

</html>

cuarto_semestre/backend/unidad_2/evaluacion/tipos/templates/tipos/crear.html
{% extends 'tipos/plantilla.html' %}

{% block contenido %}
<div class="container">
    <h1 class="text-center">Crear tipo</h1>
    <h4 class="text-center">
        <a href="{% url 'tipos:listar' %}">Listado de tipos</a>
    </h4>
    <form method="post">
        {% csrf_token %}
        {{ formulario }}
        <input type="submit" class="form-control">
    </form>
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/evaluacion/tipos/templates/tipos/listar.html
{% extends 'tipos/plantilla.html' %}

{% block contenido %}
<div class="container">
    <h1 class="text-center">Listado de tipos</h1>
    <h4 class="text-center">
        <a href="{% url 'tipos:crear' %}">Crear un tipo</a>
    </h4>
    {% if tipos %}
    <table class="table">
        <thead>
            <tr>
                <th>Tipo</th>
            </tr>
        </thead>
        <tbody>
            {% for tipo in tipos %}
            <tr>
                <td>{{ tipo.nombre }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>No hay tipos</h3>
    {% endif %}
</div>
{% endblock contenido %}

cuarto_semestre/backend/unidad_2/evaluacion/tipos/templates/tipos/plantilla.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tipos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</head>

<body>

    <!-- Barra de navegación improvisada que hice en el momento -->
    <div class="container text-center my-3">
        <div class="row">
            <div class="col">
                <h1>
                    <a href="{% url 'tipos:listar' %}" class="text-decoration-none">Tipos</a>
                </h1>
            </div>
            <div class="col">
                <h1>
                    <a href="{% url 'mascotas:listar' %}" class="text-decoration-none">Mascotas</a>
                </h1>
            </div>
        </div>
    </div>

    {% block contenido %}
    {% endblock contenido %}
</body>

</html>