cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/urls.py
from django.urls import path

from . import views

app_name = 'personas'
urlpatterns = [
    path('', views.registro, name='registro'),
    path('lista', views.lista, name='lista')
]

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/practico0002/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personas/', include('personas.urls'))
]

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/models.py
from django.db import models

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/views.py
from django.shortcuts import render

def registro(request):
    if request.method == 'POST':
        run = request.POST['run']
        nombre = request.POST['nombre']
        email = request.POST['email']
        telefono = request.POST['telefono']
        estado_civil = request.POST['estado_civil']
        genero = request.POST['genero']
        comentario = request.POST['comentario']

        registro = f'{run}|{nombre}|{email}|{telefono}|{estado_civil}|{genero}|{comentario}\n'

        with open('personas.txt', 'a') as archivo:
            archivo.write(registro)

    return render(request, 'personas/registro.html')

def lista(request):
    lista_personas = []

    with open('personas.txt', 'r') as archivo:
        for persona in archivo.readlines():
            nueva_persona = []

            for elemento in persona.split('|'):
                nueva_persona.append(elemento.rstrip('\n'))

            lista_personas.append(nueva_persona)

    print(lista_personas)

    return render(request, 'personas/lista.html', {
        'lista_personas': lista_personas
    })

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/templates/personas/lista.html
{% extends 'personas/plantilla.html' %}

{% block cuerpo %}

<div class="container">
    <h1 class="text-center">Personas registradas</h1>
    
    <p class="text-center"><a href="{% url 'personas:registro' %}">Registrarse</a></p>
</div>
<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
                    <td>Run</td>
                    <td>Nombre</td>
                    <td>Correo</td>
                    <td>Teléfono</td>
                    <td>Estado civil</td>
                    <td>Género</td>
                    <td>Comentario</td>
                </tr>
            </thead>

            <tbody>
                {% for persona in lista_personas %}
                <tr>
                    {% for elemento in persona %}
                    <td>{{ elemento }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock cuerpo %}

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/templates/personas/plantilla.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Personas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>
<body>
    {% block cuerpo %}
    {% endblock cuerpo %}
</body>
</html>

cuarto_semestre/backend/unidad_1/ejercicios/django/practico0002/personas/templates/personas/registro.html
{% extends 'personas/plantilla.html' %}

{% block cuerpo %}

<div class="container">
    <h1 class="text-center">Registro de personas</h1>

    <p class="text-center"><a href="{% url 'personas:lista' %}">Ver lista de personas</a></p>

    <form method="post" class="form row needs-validation" id="formulario" novalidate>
        {% csrf_token %}

        <!-- Run -->
        <label for="run" class="form-label">Run</label>
        <input type="text" name="run" id="run" class="form-control" required pattern="\d{1,2}\.\d{3}\.\d{3}-[\dKk]">

        <!-- Nombre -->
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" name="nombre" id="nombre" class="form-control" required pattern=".*\S.*">

        <!-- Email -->
        <label for="email" class="form-label">Email</label>
        <input type="email" id="email" name="email" class="form-control" required>

        <!-- Teléfono -->
        <label for="telefono" class="form-label">Teléfono</label>
        <input type="tel" name="telefono" id="telefono" class="form-control" required pattern="\+?\d{1,}">

        <!-- Estado civil -->
        <label for="estado_civil" class="form-label">Estado civil</label>
        <select name="estado_civil" id="estado_civil" class="form-select">
            <option value="Casad@">Casad@</option>
            <option value="Solter@">Solter@</option>
            <option value="Viud@">Viud@</option>
            <option value="Divorciad@">Divorciad@</option>
        </select>
        <br>

        <!-- Género -->
        <label class="form-label">Género: </label>
        <div class="form-check">
            <input type="radio" name="genero" id="masculino" class="form-check-input" value="Masculino" checked>
            <label for="masculino" class="form-check-label">Masculino</label>
        </div>
        <div class="form-check">
            <input type="radio" name="genero" id="femenino" class="form-check-input" value="Femenino">
            <label for="femenino" class="form-check-label">Femenino</label>
        </div>
        <div class="form-check">
            <input type="radio" name="genero" id="no_binario" class="form-check-input" value="No binario">
            <label for="no_binario" class="form-check-label">No binario</label>
        </div>
        <br>

        <!-- Comentario -->
        <label for="comentario" class="form-label">Comentario</label>
        <textarea name="comentario" id="comentario" cols="30" rows="5" class="form-control" requiren minlength="40"
            maxlength="300"></textarea>

        <!-- Enviar -->
        <div class="col text-center mt-3">
            <input type="submit" value="Registrar" class="btn btn-primary">
        </div>
    </form>
</div>

<script>
    const formulario = document.getElementById('formulario')
    formulario.addEventListener('submit', (evento) => {
        if (!formulario.checkValidity()) {
            evento.preventDefault()
            evento.stopPropagation()
        }

        formulario.classList.add('was-validated')
    })
</script>
{% endblock cuerpo %}